import {
  ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ArrowUpTrayIcon as ArrowUpTrayIconMini,
  XMarkIcon as XMarkIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  CheckIcon as CheckIconMini,
} from "@heroicons/react/20/solid";
import {
  InformationCircleIcon,
  HomeIcon as HomeIcon,
  QuestionMarkCircleIcon as HelpIcon,
  PhoneIcon,
  ClipboardDocumentListIcon as InvoiceIcon,
  ArrowRightOnRectangleIcon as LogoutIcon,
  Cog8ToothIcon as SettingIcon,
  PaperAirplaneIcon as PaperAirplane,
  ArrowDownTrayIcon as DownoldIcon,
  ChevronDownIcon as ArrowDownIcon,
  Bars3Icon as BurgerIcon,
  TrashIcon as DeleteIcon,
  PencilIcon as EditIcon,
  BuildingLibraryIcon as BankIcon,
  PlusSmallIcon as PlusIcon,
} from "@heroicons/react/24/outline";

export {
  ErrorIconMini,
  CheckCircleIconMini,
  EyeIconMini,
  EyeSlashIconMini,
  ChevronLeftIconMini,
  ArrowUpTrayIconMini,
  XMarkIconMini,
  InformationCircleIconMini,
  InformationCircleIcon,
  CheckIconMini,
  HomeIcon,
  HelpIcon,
  PhoneIcon,
  InvoiceIcon,
  LogoutIcon,
  SettingIcon,
  PaperAirplane,
  DownoldIcon,
  BurgerIcon,
  DeleteIcon,
  EditIcon,
  BankIcon,
  ArrowDownIcon,
  PlusIcon,
};
