import {
  ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ArrowUpTrayIcon as ArrowUpTrayIconMini,
  XMarkIcon as XMarkIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  CheckIcon as CheckIconMini,
 Bars3CenterLeftIcon as  BarsIcon
} from "@heroicons/react/20/solid";
import { InformationCircleIcon ,
  HomeIcon as HomeIcon,
  QuestionMarkCircleIcon as HelpIcon,
  PhoneIcon as PhoneIcon,
  ClipboardDocumentListIcon as InvoiceIcon,
  ArrowRightOnRectangleIcon as LogoutIcon,
  Cog8ToothIcon as SettingIcon,
  PaperAirplaneIcon as PaperAirplane,
  ArrowDownTrayIcon as ArrowDoewnIcon,
  Bars3Icon as BurgerIcon,
  TrashIcon as DeleteIcon,
  PencilIcon as EditIcon,
  BuildingLibraryIcon as BankIcon,
  MagnifyingGlassIcon as SearchIcon,
  ChevronUpDownIcon as ChevronIcon ,
  ChevronLeftIcon as ArrowLeft ,
  ChevronRightIcon as ArrowRight ,
  
} from "@heroicons/react/24/outline";

export {
  ErrorIconMini,
  CheckCircleIconMini,
  EyeIconMini,
  EyeSlashIconMini,
  ChevronLeftIconMini,
  ArrowUpTrayIconMini,
  XMarkIconMini,
  InformationCircleIconMini,
  InformationCircleIcon,
  CheckIconMini,
  HomeIcon,
  HelpIcon,
  PhoneIcon,
  InvoiceIcon,
  LogoutIcon,
  SettingIcon,
  PaperAirplane,
  ArrowDoewnIcon,
  BurgerIcon,
  DeleteIcon,
  EditIcon,
  BankIcon,
  SearchIcon,
  ChevronIcon,
  BarsIcon,
  ArrowRight,
  ArrowLeft
};
